# Site settings
title: Eric Akaoka
email: eric@ericakaoka.com
description: > # this means to ignore newlines until "baseurl:"
  Digital product designer and photographer from Toronto, Canada.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ericakaoka.com" # the base hostname & protocol for your site
twitter_username: akaoka
github_username:  akaoka
host: 0.0.0.0

# Build settings
markdown: kramdown
